name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: 1//03qkR9YGbrANQCgYIARAAGAMSNwF-L9IrA7UE3iKvTKOYUnQ53DcDk4dRFrtW_DWpe-nwj52JPIf_cpMaTlWPlUT07r9XzCQy6Q0
        run: firebase deploy --only hosting --token $FIREBASE_TOKEN
